version: 2.1
executors:
  node_stretch:
    docker:
      - image: circleci/node:8.12.0-stretch-browsers
commands:
  install_deps_and_run_tests:
    parameters:
      npm_run_test_command:
        type: string
jobs:
  unit_tests:
    working_directory: ~/repo
    executor: node_stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-v0-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-cache-v0-{{ .Branch }}-
            - npm-cache-v0-
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-v0-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run:
          name: Unit Tests
          command: ci:test:lib:unit
  integration_tests:
    working_directory: ~/repo
    executor: node_stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-v0-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-cache-v0-{{ .Branch }}-
            - npm-cache-v0-
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-v0-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run:
          name: Integration Tests
          command: ci:test:lib:integration
workflows:
  version: 2
  tests:
    jobs:
      - unit_tests:
          filters:
            branches:
              only: master
      - integration_tests:
          filters:
            branches:
              only: master
